name: 'Publish a release'
description: ''
inputs:
  github_token:
    description: 'The Bots token. Usually configured in the repo settings'
    required: false
    default: ${{ github.token }}
  automatic_release_tag: 
    description: Tag name to use for automatic releases, e.g latest.	
    required: false
    default: null
  prerelease: 
    description: Mark this release as a pre-release?	
    required: false
    default: false
  draft: 
    description: Mark this release as a draft?	
    required: false
    default: false
runs:
  using: "composite"
  steps:
    - name: Set asset name
      shell: bash
      run: echo '::set-output name=FILE_NAME::${{ github.event.repository.name }}-${{ github.ref_name }}'
      id: asset

    - name: "Create release zip"
      shell: bash
      run: |
        cd .. && zip -r ${{ steps.asset.outputs.FILE_NAME }}.zip . --exclude=*/node_modules/* --exclude=*/.git/* --exclude=*/.github/* --exclude=*/gulpfile.js --exclude=*/.DS_Store --exclude=*/package.json --exclude=*/package-lock.json --exclude=*/project-folders.json

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ inputs.github_token }}"
        automatic_release_tag: ${{ inputs.automatic_release_tag }}
        prerelease: ${{ inputs.prerelease }}
        draft: ${{ inputs.draft }}
        files: ../${{ steps.asset.outputs.FILE_NAME }}.zip